# Generated by Django 4.1.2 on 2022-10-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
