# Generated by Django 4.1.2 on 2022-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_notes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/img'),
        ),
    ]
