# Generated by Django 4.1.2 on 2022-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_notes_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='picture',
            field=models.ImageField(blank=True, default='static/img/images/body.jpg', null=True, upload_to='static/img/images'),
        ),
    ]
